import Head from 'next/head';
import { FC, ReactNode } from 'react';

interface LayoutProps {
  children?: ReactNode;
  title?: string;
}

const Layout: FC<LayoutProps> = ({ children, title = 'NASA' }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">{children}</main>
    </>
  );
};

export default Layout;
